# permissions for end users to view verrazzanocoherenceworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzanocoherenceworkload-viewer-role
rules:
- apiGroups:
  - oam.verrazzano.io
  resources:
  - verrazzanocoherenceworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oam.verrazzano.io
  resources:
  - verrazzanocoherenceworkloads/status
  verbs:
  - get
