# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# Example of using the VerrazzanoHelidonWorkload as a "generic" workload type to implement custom security
# settings, which is not supported by the OAM ContainerizedWorkload
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: springboot-generic-component
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoHelidonWorkload
    metadata:
      name: springboot-generic-workload
      labels:
        app: springboot-generic
        version: v1
    spec:
      deploymentTemplate:
        metadata:
          name: springboot-generic-deployment
        podSpec:
          securityContext:
            runAsUser: 1000  # run as non-root user; does not have exist in the container /etc/passwd
            runAsGroup: 1000 # run as non-root group; does not have exist in the container /etc/group
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: springboot-container
              image: "ghcr.io/verrazzano/example-springboot:1.0.0-1-20220513221156-7da0d32"
              ports:
                - containerPort: 8080
                  name: springboot
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
