# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# Example of using the VerrazzanoHelidonWorkload as a "generic" workload type to implement custom security
# settings, which is not supported by the OAM ContainerizedWorkload
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: springboot-generic-appconf
  annotations:
    version: v1.0.0
    description: "Spring Boot application"
spec:
  components:
    - componentName: springboot-generic-component
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: MetricsTrait
            spec:
              scraper: verrazzano-system/vmi-system-prometheus-0
              path: "/actuator/prometheus"
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: generic-workload-ingress
            spec:
              rules:
                - paths:
                    - path: "/"
                      pathType: Prefix

