# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

OpensearchSpec:
  name: opensearch
  security:
    config:
      securityConfigSecret:
        name: securityconfig-secret
      adminSecret:
        name: tls-cert
    tls:
      transport:
        generate: false
        secret:
          name: tls-cert
        adminDn: ["CN=opensearch.verrazzano-logging.svc.cluster.local,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA"]
        nodesDn: ["CN=opensearch.verrazzano-logging.svc.cluster.local,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA"]
      http:
        generate: false
        secret:
          name: tls-cert
  general:
    httpPort: 9200
    serviceName: opensearch
    version: 2.3.0
    drainDataNodes: true
  dashboards:
    additionalConfig:
      server.name: opensearch-dashboards
      opensearch_security.auth.type: "proxy"
      opensearch_security.proxycache.user_header: "X-WEBAUTH-USER"
      opensearch_security.proxycache.roles_header: "x-proxy-roles"
      opensearch.requestHeadersAllowlist: securitytenant,Authorization,x-forwarded-for,X-WEBAUTH-USER,x-proxy-roles
      opensearch_security.multitenancy.enabled: "false"
    tls:
      enable: true
      generate: true
    version: 2.3.0
    enable: true
    replicas: 1