apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: hello-helidon
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: hello-helidon
  podMetricsEndpoints:
    - targetPort: 8081


